Do not assign to read-only property (#3647)
Without this change, we see the following error on staging:

    TypeError: Cannot set property transports of #<Logger> which has only a getter
        at 40066 (/app/.next/server/chunks/1701.js:1:352)
        at __webpack_require__ (/app/.next/server/webpack-runtime.js:1:161)
        at 5183 (/app/.next/server/chunks/5183.js:1:139)
        at __webpack_require__ (/app/.next/server/webpack-runtime.js:1:161)
        at 4205 (/app/.next/server/chunks/5127.js:1:1956)
        at Function.__webpack_require__ (/app/.next/server/webpack-runtime.js:1:161)
        at runNextTicks (node:internal/process/task_queues:60:5)
        at listOnTimeout (node:internal/timers:540:9)
        at process.processTimers (node:internal/timers:514:7)
        at async eq (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:107:38102)

Co-authored-by: Robert Helmer <rhelmer@mozilla.com>