Make sure React is in scope for email's BreachCard
We're seeing the following errors in the server log:

> ReferenceError: React is not defined

Unfortunately, I don't yet know how to reproduce it. (I seem to
have been able to in the past, since I did include the import
elsewhere.)

It might be that we can avoid needing that import by adding

    "jsx": "react-jsx",

to our `compilerOptions` in tsconfig.cronjobs.json. However, I'd
like to understand what's going on, and if that resolves it, before
doing that.

Some relevant resources:
- https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-different-in-the-new-transform
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#jsx-factories
- https://www.typescriptlang.org/tsconfig/#jsx
- https://www.typescriptlang.org/docs/handbook/jsx.html