Remove waitForNavigation calls
The CI logs have the following eror pointing to those calls:

> Error: page.waitForNavigation: net::ERR_TOO_MANY_REDIRECTS

Additionally, the API is deprecated as a source of raciness, and it
didn't seem to be necessary anyway.

I've also split up the password selectors for signing in and
signing up, since they're different forms with different labels,
and thus trying to come up with a selector that matched both is a
losing battle.