Upgrade Storybook to be compatible with latest Next.js
What I did:
- npx storybook@latest upgrade.
- Change to `moduleResolution: bundler` in tsconfig, because otherwise
  importing Storybook types failed.
- Add explicit paths to tsconfig for Glean, which doesn't seem to work
  well with moduleResolution: bundler without it.

For some more background on the moduleResolutionChange, this is the
error message I faced on `npm run build`:

        .storybook/main.ts:6:38
        Type error: Cannot find module '@storybook/nextjs' or its corresponding type declarations.
          There are types at 'blurts-server/node_modules/@storybook/nextjs/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.